HOST=arm-linux-androideabi
SOURCE_DIR=hyphen-2.7.1
DEST_DIR=$(shell pwd)/out
PKG_CONFIG_PATH=$(DEST_DIR)/lib/pkgconfig

all: configure build install

configure:
	cd $(SOURCE_DIR); PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) ./configure --host=$(HOST) --prefix=$(DEST_DIR)

build:
	cd $(SOURCE_DIR); make

install:
	cd $(SOURCE_DIR); make install

clean:
	cd $(SOURCE_DIR); make clean

